- hosts: mygroup
  name: This is my HOST

  tasks:
          - name: creating a yum repository for docker
            yum_repository:
                  name:  docker
                  baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
                  description: "docker"
                  gpgcheck: no
                  enabled: true

          - name: installing required packages to configure webserver
            package:
                  name: ["python36","docker-ce-3:18.09.1-3.el7.x86_64","httpd"] 
                  state: present
            register: p

       #  - debug:
       #      var: p

          - name:  installing docker-python dependency
            command:
                  cmd: "pip3 install docker"

          - name: starting docker service
            service:
                  name: "docker"
                  state: started
                  enabled: yes
            register: ds

       #  - debug:
       #      var: ds

          - name: starting httpd service
            service:
                  name: "httpd"
                  state: started
                  enabled: yes
            register: hs

          - name: Stopping Firewall
            service:
                    name: "firewalld"
                    state: stopped

        # - debug:
        #     var: hs

          - name: pulling docker image
            docker_image:
                  name: httpd
                  source: pull
                  state: present
            register: i

        # - debug:
        #     var: i

          - name: making folder for webpages
            file:
                    name: /web
                    state: directory
            ignore_errors: true

          - name: copying webpage to host
            copy:
                  src: /web/index.html
                  dest: /web
            register: c

          - name: launching a docker container
            docker_container:
                  name: task_os
                  state: started
                  image: httpd
                  expose:
                          - '80'
                  ports:
                          - 8118:80
                  volumes:
                          - /web/:/usr/local/apache2/htdocs
